# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
                ('state', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('endpoint_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('peer_id', models.CharField(db_index=True, max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('public', models.BooleanField()),
                ('endpoint_type', models.CharField(max_length=255)),
                ('endpoint_params', models.TextField()),
                ('current_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_of', to='panoramix_service.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(null=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_messages', to='panoramix_service.Cycle')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_messages', to='panoramix_service.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('peer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key_type', models.IntegerField()),
                ('crypto_backend', models.CharField(max_length=255)),
                ('crypto_params', models.TextField()),
                ('key_data', models.TextField(unique=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='panoramix_service.Peer'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='panoramix_service.Endpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together=set([('peer', 'owner_key_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together=set([('endpoint', 'cycle')]),
        ),
    ]
